### ISSUE TITLE
SRS buttons only show color when hovered over. 

### ISSUE THREAD

**Issue by jarodise** [blueteafrog/logseq-oxfordblue-theme#3]
Very nice theme, but the SRS interface buttons, e.g. review, remember only show background color when the mouse cursor is hovered over, otherwise no color at all, which make them less obvious.  Not sure it's a feature or a bug, but I think it is better to show the background color of these buttons by default. especially for cards query, when the color is by default transparent, it's very hard to see where the review button is. 

![CleanShot 2022-02-17 at 10 58 10@2x](https://user-images.githubusercontent.com/15899808/154430901-73b921c1-7731-4e36-abc4-b54c3f5c62bd.png)

**Comment by d5technews** [comment]
Hi, thank you for the feedback. Definitely a bug. Which version of logseq are you using?

**Comment by jarodise** [comment]
0.6.1

**Comment by d5technews** [comment]
Should be fixed. Please update via the marketplace and let me know! :)

**Comment by jarodise** [comment]
Thanks for the update, I can see some change on my end now, the review button still doesn't have background color by default ,but right now there is a frame around it, the background color shows when the mouse cursor is hovered over, I still think it would be nice to show the background color of the buttons all the time. 

![CleanShot 2022-02-25 at 16 05 20@2x](https://user-images.githubusercontent.com/15899808/155720406-33e8ccfc-1f8b-43c2-914b-a557b958e02a.png)

**Comment by d5technews** [comment]
Sure, I'll revisit over the weekend.

**Comment by d5technews** [comment]
Hello, I implemented a background color for the SRS interface buttons (following the style guide of the default theme). I think they are a bit too distracting, but if you think yourself and other users would find it helpful or beneficial, then I don't mind applying the update. Please see attached screenshots of default logseq implementation and oxford blue implementation. I'll update it on the marketplace once I receive your feedback.
![Screen Shot 2022-03-05 at 15 43 41](https://user-images.githubusercontent.com/7694090/156903903-46a0ca80-c8eb-4dbf-9bee-38f5ff6e9f79.png)
![Screen Shot 2022-03-05 at 15 45 31](https://user-images.githubusercontent.com/7694090/156903904-93455418-4482-49d8-beed-f73862484acb.png)

**Comment by jarodise** [comment]
Hi, thanks for the communication. I personally find the hover over animation more distracting than simply having the background color applied all the time. I like your implementation of using more subtle colors than the default one.

**Comment by d5technews** [comment]
Done. It is published with the new button style. Thank you for your feedback! Please let me know if you experience any issues

**Comment by jarodise** [comment]
Will do ,thanks for the update, really appreciate the work you put in. :)
